[package]
name = "get_pw"
version = "0.1.0"
authors = ["Stefan Hoppe <stefan_hoppe@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyring = "0.8.0"

